repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args:
          - --max-line-length=88
          - --ignore=E203,W503,F403,F405 # F403 and F405 ignore warnings from * imports in __init__.py files
# -   repo: https://github.com/PyCQA/docformatter
#     rev: v1.7.5  # Use the latest version
#     hooks:
#     -   id: docformatter
#         args: ["--in-place", "--style=google", "--wrap-summaries=88", "--wrap-descriptions=88"]
# HACK: replace with an actual docformatter version when InvalidManifestError is fixed
-   repo: https://github.com/PyCQA/docformatter
    rev: 06907d0
    hooks:
    -   id: docformatter
        additional_dependencies: [tomli]
        args: ["--in-place", "--style=google", "--wrap-summaries=88", "--wrap-descriptions=88"]
        files: ^rlaopt/.*\.py$
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args: ["--convention=google"]
        additional_dependencies: [toml]
        files: ^rlaopt/.*\.py$
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.0  # Use the specific version of clang-format you prefer
    hooks:
      - id: clang-format
        files: ^rlaopt/.*\.(cpp|hpp|cc|h|c|cu|cuh)$  # Extensions to format
