name: Pre-commit checks

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Sync development environment
        run: uv sync --locked --no-default-groups --group dev --python "${{ inputs.python-version }}"

      - name: Run pre-commit on changed files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            uv run --locked --no-sync pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref HEAD
          else
            uv run --locked --no-sync pre-commit run --from-ref ${{ github.event.before }} --to-ref ${{ github.sha }}
          fi
